;
; listview watermark: resource 502
;
;
; about dialog watermark: resource 503
;
;
; edit	P2kcommander.dlg for title text
;		About.dlg
;
;
; appicon: resource 4000
;
AboutTextColor	equ 0 
AboutLinkColor  equ 0ff0000h
AboutHotLinkColor  equ 0ffh

FontMS            db       'MS Sans Serif',0
FontMS2           db       'Tahoma',0
FontMSfixed       db       'Fixedsys',0
EmptyDirMark	db "www.el-co.hu/smf",0
EmptyDirMarks5vi db "5",0

MM_Url			db "http://s5vi.vxxxstuff.com",0
MM_Url2			db "s5vi@freemail.hu",0
MM_Url3			db "http://www.el-co.hu/smf",0
MM_Url4			db "http://www.mobilerated.com",0
Esubject		db "About P2kCommander V6.0.0",0
Ebody			db "I run P2kCommander, and I think ...",0

